name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou"
database_id = "5738bb84-3a9d-42d9-b1be-506bd9e8bc7a"

[version_metadata]
binding = "CF_VERSION_METADATA"
